name: GitHub Actions Build 7Plus
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      env:
        ACCESS_TOKEN: ${{ secrets.WANLUM }}
        BUILD_SCRIPT: npm install && npm run build

