# actions's name
name: Seven Plus Eduction System Action

# Controls when the action will run 
on: 
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push: 
    branches: [$default-branch]
  pull_request: 
    branches: [$default-branch]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2